### ISSUE TITLE
大佬能做下腾讯翻译君的api吗

### ISSUE THREAD

**Issue by AlifeLine** [Chinese-boy/Many-Translaters#1]
感觉那个翻译更好

**Comment by JieningYu** [comment]
翻译“bear"之后爬下来的
![image](https://user-images.githubusercontent.com/61787533/84495174-4e527c80-acdd-11ea-8370-0a30b2345b10.png)
![image](https://user-images.githubusercontent.com/61787533/84495189-54e0f400-acdd-11ea-97e0-186d9bc85d6d.png)

**Comment by AlifeLine** [comment]
谢谢，我已经自己写了一个了，不过headers里面有两个参数不知道怎么生成的，只能每次要用的时候抓包替换一下



---原始邮件---
发件人: "JieningYu"<notifications@github.com&gt;
发送时间: 2020年6月12日(周五) 晚上6:49
收件人: "Chinese-boy/Many-Translaters"<Many-Translaters@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"AlifeLines"<962714000@qq.com&gt;;
主题: Re: [Chinese-boy/Many-Translaters] 大佬能做下腾讯翻译君的api吗 (#1)




 
翻译“bear"之后爬下来的
